package karrus.shared.hibernate;

import java.util.Date;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * AlAlarmClosedId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class AlAlarmClosedId extends LightEntity implements java.io.Serializable {

	private Date openingTimestamp;
	private String type;
	private String source;

	public AlAlarmClosedId() {
	}

	public AlAlarmClosedId(Date openingTimestamp, String type, String source) {
		this.openingTimestamp = openingTimestamp;
		this.type = type;
		this.source = source;
	}

	public Date getOpeningTimestamp() {
		return this.openingTimestamp;
	}

	public void setOpeningTimestamp(Date openingTimestamp) {
		this.openingTimestamp = openingTimestamp;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlAlarmClosedId))
			return false;
		AlAlarmClosedId castOther = (AlAlarmClosedId) other;

		return ((this.getOpeningTimestamp() == castOther.getOpeningTimestamp())
				|| (this.getOpeningTimestamp() != null && castOther.getOpeningTimestamp() != null
						&& this.getOpeningTimestamp().equals(castOther.getOpeningTimestamp())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getSource() == castOther.getSource()) || (this.getSource() != null
						&& castOther.getSource() != null && this.getSource().equals(castOther.getSource())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOpeningTimestamp() == null ? 0 : this.getOpeningTimestamp().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getSource() == null ? 0 : this.getSource().hashCode());
		return result;
	}

	private static final long serialVersionUID = 1L;

}
