package karrus.shared.hibernate;

import java.util.Date;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * AlAlarmOpened generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class AlAlarmOpened extends LightEntity implements java.io.Serializable {

	private AlAlarmOpenedId id;
	private Date acknowledgementTimestamp;
	private String status;

	public AlAlarmOpened() {
	}

	public AlAlarmOpened(AlAlarmOpenedId id, String status) {
		this.id = id;
		this.status = status;
	}

	public AlAlarmOpened(AlAlarmOpenedId id, Date acknowledgementTimestamp, String status) {
		this.id = id;
		this.acknowledgementTimestamp = acknowledgementTimestamp;
		this.status = status;
	}

	public AlAlarmOpenedId getId() {
		return this.id;
	}

	public void setId(AlAlarmOpenedId id) {
		this.id = id;
	}

	public Date getAcknowledgementTimestamp() {
		return this.acknowledgementTimestamp;
	}

	public void setAcknowledgementTimestamp(Date acknowledgementTimestamp) {
		this.acknowledgementTimestamp = acknowledgementTimestamp;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	private static final long serialVersionUID = 1L;

}
