package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * Camera generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class Camera extends LightEntity implements java.io.Serializable {

	private String id;
	private Double longitude;
	private Double latitude;
	private String fluxRtsp;
	private String streamingUrl;
	private String ip;
	private Integer snapshotFrequencys;
	private String lastSnapshot;
	private String name;
	private Integer snapshotDeleteOlderThanMin;
	private Boolean streamingActive;
	private Integer snapshotDelay;
	private String port;

	public Camera() {
	}

	public Camera(String id) {
		this.id = id;
	}

	public Camera(String id, Double longitude, Double latitude, String fluxRtsp, String streamingUrl, String ip,
			Integer snapshotFrequencys, String lastSnapshot, String name, Integer snapshotDeleteOlderThanMin,
			Boolean streamingActive, Integer snapshotDelay, String port) {
		this.id = id;
		this.longitude = longitude;
		this.latitude = latitude;
		this.fluxRtsp = fluxRtsp;
		this.streamingUrl = streamingUrl;
		this.ip = ip;
		this.snapshotFrequencys = snapshotFrequencys;
		this.lastSnapshot = lastSnapshot;
		this.name = name;
		this.snapshotDeleteOlderThanMin = snapshotDeleteOlderThanMin;
		this.streamingActive = streamingActive;
		this.snapshotDelay = snapshotDelay;
		this.port = port;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getFluxRtsp() {
		return this.fluxRtsp;
	}

	public void setFluxRtsp(String fluxRtsp) {
		this.fluxRtsp = fluxRtsp;
	}

	public String getStreamingUrl() {
		return this.streamingUrl;
	}

	public void setStreamingUrl(String streamingUrl) {
		this.streamingUrl = streamingUrl;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getSnapshotFrequencys() {
		return this.snapshotFrequencys;
	}

	public void setSnapshotFrequencys(Integer snapshotFrequencys) {
		this.snapshotFrequencys = snapshotFrequencys;
	}

	public String getLastSnapshot() {
		return this.lastSnapshot;
	}

	public void setLastSnapshot(String lastSnapshot) {
		this.lastSnapshot = lastSnapshot;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSnapshotDeleteOlderThanMin() {
		return this.snapshotDeleteOlderThanMin;
	}

	public void setSnapshotDeleteOlderThanMin(Integer snapshotDeleteOlderThanMin) {
		this.snapshotDeleteOlderThanMin = snapshotDeleteOlderThanMin;
	}

	public Boolean getStreamingActive() {
		return this.streamingActive;
	}

	public void setStreamingActive(Boolean streamingActive) {
		this.streamingActive = streamingActive;
	}

	public Integer getSnapshotDelay() {
		return this.snapshotDelay;
	}

	public void setSnapshotDelay(Integer snapshotDelay) {
		this.snapshotDelay = snapshotDelay;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	private static final long serialVersionUID = 1L;

}
