package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * CtCountDataLast generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class CtCountDataLast extends LightEntity implements java.io.Serializable {

	private CtCountDataLastId id;
	private int periodSec;
	private Integer count;
	private Integer countLong;
	private Double occupancy;
	private Double speed;
	private Integer latency;

	public CtCountDataLast() {
	}

	public CtCountDataLast(CtCountDataLastId id, int periodSec) {
		this.id = id;
		this.periodSec = periodSec;
	}

	public CtCountDataLast(CtCountDataLastId id, int periodSec, Integer count, Integer countLong, Double occupancy,
			Double speed, Integer latency) {
		this.id = id;
		this.periodSec = periodSec;
		this.count = count;
		this.countLong = countLong;
		this.occupancy = occupancy;
		this.speed = speed;
		this.latency = latency;
	}

	public CtCountDataLastId getId() {
		return this.id;
	}

	public void setId(CtCountDataLastId id) {
		this.id = id;
	}

	public int getPeriodSec() {
		return this.periodSec;
	}

	public void setPeriodSec(int periodSec) {
		this.periodSec = periodSec;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getCountLong() {
		return this.countLong;
	}

	public void setCountLong(Integer countLong) {
		this.countLong = countLong;
	}

	public Double getOccupancy() {
		return this.occupancy;
	}

	public void setOccupancy(Double occupancy) {
		this.occupancy = occupancy;
	}

	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	public Integer getLatency() {
		return this.latency;
	}

	public void setLatency(Integer latency) {
		this.latency = latency;
	}

	private static final long serialVersionUID = 1L;

}
