package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * CtLane generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class CtLane extends LightEntity implements java.io.Serializable {

	private CtLaneId id;
	private String road;
	private String way;
	private String position;

	public CtLane() {
	}

	public CtLane(CtLaneId id) {
		this.id = id;
	}

	public CtLane(CtLaneId id, String road, String way, String position) {
		this.id = id;
		this.road = road;
		this.way = way;
		this.position = position;
	}

	public CtLaneId getId() {
		return this.id;
	}

	public void setId(CtLaneId id) {
		this.id = id;
	}

	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	public String getWay() {
		return this.way;
	}

	public void setWay(String way) {
		this.way = way;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	private static final long serialVersionUID = 1L;

}
