package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * CtMagDiag generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class CtMagDiag extends LightEntity implements java.io.Serializable {

	private CtMagDiagId id;
	private Integer count;
	private Double occupancy;
	private Double batteryLevel;
	private Double rssiAverage;
	private Double rssiStd;
	private Double lqiAverage;
	private Double lqiStd;

	public CtMagDiag() {
	}

	public CtMagDiag(CtMagDiagId id) {
		this.id = id;
	}

	public CtMagDiag(CtMagDiagId id, Integer count, Double occupancy, Double batteryLevel, Double rssiAverage,
			Double rssiStd, Double lqiAverage, Double lqiStd) {
		this.id = id;
		this.count = count;
		this.occupancy = occupancy;
		this.batteryLevel = batteryLevel;
		this.rssiAverage = rssiAverage;
		this.rssiStd = rssiStd;
		this.lqiAverage = lqiAverage;
		this.lqiStd = lqiStd;
	}

	public CtMagDiagId getId() {
		return this.id;
	}

	public void setId(CtMagDiagId id) {
		this.id = id;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Double getOccupancy() {
		return this.occupancy;
	}

	public void setOccupancy(Double occupancy) {
		this.occupancy = occupancy;
	}

	public Double getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(Double batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	public Double getRssiAverage() {
		return this.rssiAverage;
	}

	public void setRssiAverage(Double rssiAverage) {
		this.rssiAverage = rssiAverage;
	}

	public Double getRssiStd() {
		return this.rssiStd;
	}

	public void setRssiStd(Double rssiStd) {
		this.rssiStd = rssiStd;
	}

	public Double getLqiAverage() {
		return this.lqiAverage;
	}

	public void setLqiAverage(Double lqiAverage) {
		this.lqiAverage = lqiAverage;
	}

	public Double getLqiStd() {
		return this.lqiStd;
	}

	public void setLqiStd(Double lqiStd) {
		this.lqiStd = lqiStd;
	}

	private static final long serialVersionUID = 1L;

}
