package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * CtRpDiag generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class CtRpDiag extends LightEntity implements java.io.Serializable {

	private CtRpDiagId id;
	private Double batteryLevel;
	private Double loss;
	private Double rssiAverage;
	private Double rssiStd;
	private Double lqiAverage;
	private Double lqiStd;

	public CtRpDiag() {
	}

	public CtRpDiag(CtRpDiagId id) {
		this.id = id;
	}

	public CtRpDiag(CtRpDiagId id, Double batteryLevel, Double loss, Double rssiAverage, Double rssiStd,
			Double lqiAverage, Double lqiStd) {
		this.id = id;
		this.batteryLevel = batteryLevel;
		this.loss = loss;
		this.rssiAverage = rssiAverage;
		this.rssiStd = rssiStd;
		this.lqiAverage = lqiAverage;
		this.lqiStd = lqiStd;
	}

	public CtRpDiagId getId() {
		return this.id;
	}

	public void setId(CtRpDiagId id) {
		this.id = id;
	}

	public Double getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(Double batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	public Double getLoss() {
		return this.loss;
	}

	public void setLoss(Double loss) {
		this.loss = loss;
	}

	public Double getRssiAverage() {
		return this.rssiAverage;
	}

	public void setRssiAverage(Double rssiAverage) {
		this.rssiAverage = rssiAverage;
	}

	public Double getRssiStd() {
		return this.rssiStd;
	}

	public void setRssiStd(Double rssiStd) {
		this.rssiStd = rssiStd;
	}

	public Double getLqiAverage() {
		return this.lqiAverage;
	}

	public void setLqiAverage(Double lqiAverage) {
		this.lqiAverage = lqiAverage;
	}

	public Double getLqiStd() {
		return this.lqiStd;
	}

	public void setLqiStd(Double lqiStd) {
		this.lqiStd = lqiStd;
	}

	private static final long serialVersionUID = 1L;

}
