package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * LeafMarker generated by hbm2java.
 *
 * Custom pojo generation. Generated: 16 déc. 2019 10:13:37.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class LeafMarker extends LightEntity implements java.io.Serializable {

	private String id;
	private Double latitude;
	private Double longitude;
	private String htmlMarker;
	private String htmlPopup;
	private String type;

	public LeafMarker() {
	}

	public LeafMarker(String id) {
		this.id = id;
	}

	public LeafMarker(String id, Double latitude, Double longitude, String htmlMarker, String htmlPopup, String type) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
		this.htmlMarker = htmlMarker;
		this.htmlPopup = htmlPopup;
		this.type = type;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getHtmlMarker() {
		return this.htmlMarker;
	}

	public void setHtmlMarker(String htmlMarker) {
		this.htmlMarker = htmlMarker;
	}

	public String getHtmlPopup() {
		return this.htmlPopup;
	}

	public void setHtmlPopup(String htmlPopup) {
		this.htmlPopup = htmlPopup;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	private static final long serialVersionUID = 1L;

}
