package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * LfFonctionId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class LfFonctionId extends LightEntity implements java.io.Serializable {

	private String id;
	private String fonction;

	public LfFonctionId() {
	}

	public LfFonctionId(String id, String fonction) {
		this.id = id;
		this.fonction = fonction;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LfFonctionId))
			return false;
		LfFonctionId castOther = (LfFonctionId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getFonction() == castOther.getFonction()) || (this.getFonction() != null
						&& castOther.getFonction() != null && this.getFonction().equals(castOther.getFonction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getFonction() == null ? 0 : this.getFonction().hashCode());
		return result;
	}

	private static final long serialVersionUID = 1L;

}
