package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * LfFonction generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class LfFonction extends LightEntity implements java.io.Serializable {

	private LfFonctionId id;
	private String htmlPopup;

	public LfFonction() {
	}

	public LfFonction(LfFonctionId id) {
		this.id = id;
	}

	public LfFonction(LfFonctionId id, String htmlPopup) {
		this.id = id;
		this.htmlPopup = htmlPopup;
	}

	public LfFonctionId getId() {
		return this.id;
	}

	public void setId(LfFonctionId id) {
		this.id = id;
	}

	public String getHtmlPopup() {
		return this.htmlPopup;
	}

	public void setHtmlPopup(String htmlPopup) {
		this.htmlPopup = htmlPopup;
	}

	private static final long serialVersionUID = 1L;

}
