package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * LfPolyline generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class LfPolyline extends LightEntity implements java.io.Serializable {

	private LfPolylineId id;
	private String listOfLatlngs;
	private String color;
	private String htmlPopup;

	public LfPolyline() {
	}

	public LfPolyline(LfPolylineId id) {
		this.id = id;
	}

	public LfPolyline(LfPolylineId id, String listOfLatlngs, String color, String htmlPopup) {
		this.id = id;
		this.listOfLatlngs = listOfLatlngs;
		this.color = color;
		this.htmlPopup = htmlPopup;
	}

	public LfPolylineId getId() {
		return this.id;
	}

	public void setId(LfPolylineId id) {
		this.id = id;
	}

	public String getListOfLatlngs() {
		return this.listOfLatlngs;
	}

	public void setListOfLatlngs(String listOfLatlngs) {
		this.listOfLatlngs = listOfLatlngs;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getHtmlPopup() {
		return this.htmlPopup;
	}

	public void setHtmlPopup(String htmlPopup) {
		this.htmlPopup = htmlPopup;
	}

	private static final long serialVersionUID = 1L;

}
