package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * Pmv generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class Pmv extends LightEntity implements java.io.Serializable {

	private String id;
	private String htmlPmv;
	private Boolean popupEnabled;
	private Double latitude;
	private Double longitude;
	private String type;

	public Pmv() {
	}

	public Pmv(String id) {
		this.id = id;
	}

	public Pmv(String id, String htmlPmv, Boolean popupEnabled, Double latitude, Double longitude, String type) {
		this.id = id;
		this.htmlPmv = htmlPmv;
		this.popupEnabled = popupEnabled;
		this.latitude = latitude;
		this.longitude = longitude;
		this.type = type;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHtmlPmv() {
		return this.htmlPmv;
	}

	public void setHtmlPmv(String htmlPmv) {
		this.htmlPmv = htmlPmv;
	}

	public Boolean getPopupEnabled() {
		return this.popupEnabled;
	}

	public void setPopupEnabled(Boolean popupEnabled) {
		this.popupEnabled = popupEnabled;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	private static final long serialVersionUID = 1L;

}
