package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * PolylineTraficolorId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 16 déc. 2019 10:13:37.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class PolylineTraficolorId extends LightEntity implements java.io.Serializable {

	private String originDest;
	private String zoomLevel;

	public PolylineTraficolorId() {
	}

	public PolylineTraficolorId(String originDest, String zoomLevel) {
		this.originDest = originDest;
		this.zoomLevel = zoomLevel;
	}

	public String getOriginDest() {
		return this.originDest;
	}

	public void setOriginDest(String originDest) {
		this.originDest = originDest;
	}

	public String getZoomLevel() {
		return this.zoomLevel;
	}

	public void setZoomLevel(String zoomLevel) {
		this.zoomLevel = zoomLevel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PolylineTraficolorId))
			return false;
		PolylineTraficolorId castOther = (PolylineTraficolorId) other;

		return ((this.getOriginDest() == castOther.getOriginDest()) || (this.getOriginDest() != null
				&& castOther.getOriginDest() != null && this.getOriginDest().equals(castOther.getOriginDest())))
				&& ((this.getZoomLevel() == castOther.getZoomLevel()) || (this.getZoomLevel() != null
						&& castOther.getZoomLevel() != null && this.getZoomLevel().equals(castOther.getZoomLevel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOriginDest() == null ? 0 : this.getOriginDest().hashCode());
		result = 37 * result + (getZoomLevel() == null ? 0 : this.getZoomLevel().hashCode());
		return result;
	}

	private static final long serialVersionUID = 1L;

}
