package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * PopupInfo generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class PopupInfo extends LightEntity implements java.io.Serializable {

	private PopupInfoId id;
	private String infoHtml;

	public PopupInfo() {
	}

	public PopupInfo(PopupInfoId id) {
		this.id = id;
	}

	public PopupInfo(PopupInfoId id, String infoHtml) {
		this.id = id;
		this.infoHtml = infoHtml;
	}

	public PopupInfoId getId() {
		return this.id;
	}

	public void setId(PopupInfoId id) {
		this.id = id;
	}

	public String getInfoHtml() {
		return this.infoHtml;
	}

	public void setInfoHtml(String infoHtml) {
		this.infoHtml = infoHtml;
	}

	private static final long serialVersionUID = 1L;

}
