package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * RsuDiag generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class RsuDiag extends LightEntity implements java.io.Serializable {

	private RsuDiagId id;
	private Integer powerMode;
	private Double batteryLevel;
	private Double temperatureInternal;
	private Double load;
	private Double memory;
	private Double cellularRssi;
	private Double v2xRssi;
	private Double btRssi;
	private Double gpsLatitude;
	private Double gpsLongitude;
	private Double gpsHdop;

	public RsuDiag() {
	}

	public RsuDiag(RsuDiagId id) {
		this.id = id;
	}

	public RsuDiag(RsuDiagId id, Integer powerMode, Double batteryLevel, Double temperatureInternal, Double load,
			Double memory, Double cellularRssi, Double v2xRssi, Double btRssi, Double gpsLatitude, Double gpsLongitude,
			Double gpsHdop) {
		this.id = id;
		this.powerMode = powerMode;
		this.batteryLevel = batteryLevel;
		this.temperatureInternal = temperatureInternal;
		this.load = load;
		this.memory = memory;
		this.cellularRssi = cellularRssi;
		this.v2xRssi = v2xRssi;
		this.btRssi = btRssi;
		this.gpsLatitude = gpsLatitude;
		this.gpsLongitude = gpsLongitude;
		this.gpsHdop = gpsHdop;
	}

	public RsuDiagId getId() {
		return this.id;
	}

	public void setId(RsuDiagId id) {
		this.id = id;
	}

	public Integer getPowerMode() {
		return this.powerMode;
	}

	public void setPowerMode(Integer powerMode) {
		this.powerMode = powerMode;
	}

	public Double getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(Double batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	public Double getTemperatureInternal() {
		return this.temperatureInternal;
	}

	public void setTemperatureInternal(Double temperatureInternal) {
		this.temperatureInternal = temperatureInternal;
	}

	public Double getLoad() {
		return this.load;
	}

	public void setLoad(Double load) {
		this.load = load;
	}

	public Double getMemory() {
		return this.memory;
	}

	public void setMemory(Double memory) {
		this.memory = memory;
	}

	public Double getCellularRssi() {
		return this.cellularRssi;
	}

	public void setCellularRssi(Double cellularRssi) {
		this.cellularRssi = cellularRssi;
	}

	public Double getV2xRssi() {
		return this.v2xRssi;
	}

	public void setV2xRssi(Double v2xRssi) {
		this.v2xRssi = v2xRssi;
	}

	public Double getBtRssi() {
		return this.btRssi;
	}

	public void setBtRssi(Double btRssi) {
		this.btRssi = btRssi;
	}

	public Double getGpsLatitude() {
		return this.gpsLatitude;
	}

	public void setGpsLatitude(Double gpsLatitude) {
		this.gpsLatitude = gpsLatitude;
	}

	public Double getGpsLongitude() {
		return this.gpsLongitude;
	}

	public void setGpsLongitude(Double gpsLongitude) {
		this.gpsLongitude = gpsLongitude;
	}

	public Double getGpsHdop() {
		return this.gpsHdop;
	}

	public void setGpsHdop(Double gpsHdop) {
		this.gpsHdop = gpsHdop;
	}

	private static final long serialVersionUID = 1L;

}
