package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * RsuStation generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class RsuStation extends LightEntity implements java.io.Serializable {

	private String id;
	private String serial;
	private String host;
	private Double latitude;
	private Double longitude;
	private String road;
	private String position;
	private Integer cycleCountingSec;
	private Integer cycleTravelTimeSec;
	private Integer cycleWeatherSec;
	private Integer cycleV2xSec;

	public RsuStation() {
	}

	public RsuStation(String id, String serial, String host) {
		this.id = id;
		this.serial = serial;
		this.host = host;
	}

	public RsuStation(String id, String serial, String host, Double latitude, Double longitude, String road,
			String position, Integer cycleCountingSec, Integer cycleTravelTimeSec, Integer cycleWeatherSec,
			Integer cycleV2xSec) {
		this.id = id;
		this.serial = serial;
		this.host = host;
		this.latitude = latitude;
		this.longitude = longitude;
		this.road = road;
		this.position = position;
		this.cycleCountingSec = cycleCountingSec;
		this.cycleTravelTimeSec = cycleTravelTimeSec;
		this.cycleWeatherSec = cycleWeatherSec;
		this.cycleV2xSec = cycleV2xSec;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Integer getCycleCountingSec() {
		return this.cycleCountingSec;
	}

	public void setCycleCountingSec(Integer cycleCountingSec) {
		this.cycleCountingSec = cycleCountingSec;
	}

	public Integer getCycleTravelTimeSec() {
		return this.cycleTravelTimeSec;
	}

	public void setCycleTravelTimeSec(Integer cycleTravelTimeSec) {
		this.cycleTravelTimeSec = cycleTravelTimeSec;
	}

	public Integer getCycleWeatherSec() {
		return this.cycleWeatherSec;
	}

	public void setCycleWeatherSec(Integer cycleWeatherSec) {
		this.cycleWeatherSec = cycleWeatherSec;
	}

	public Integer getCycleV2xSec() {
		return this.cycleV2xSec;
	}

	public void setCycleV2xSec(Integer cycleV2xSec) {
		this.cycleV2xSec = cycleV2xSec;
	}

	private static final long serialVersionUID = 1L;

}
