package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * SynRdtDisplay generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class SynRdtDisplay extends LightEntity implements java.io.Serializable {

	private SynRdtDisplayId id;
	private String station;
	private String content;

	public SynRdtDisplay() {
	}

	public SynRdtDisplay(SynRdtDisplayId id, String station, String content) {
		this.id = id;
		this.station = station;
		this.content = content;
	}

	public SynRdtDisplayId getId() {
		return this.id;
	}

	public void setId(SynRdtDisplayId id) {
		this.id = id;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	private static final long serialVersionUID = 1L;

}
