package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * SynTtDisplay generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class SynTtDisplay extends LightEntity implements java.io.Serializable {

	private SynTtDisplayId id;
	private String origin;
	private String destination;
	private String content;

	public SynTtDisplay() {
	}

	public SynTtDisplay(SynTtDisplayId id, String origin, String destination, String content) {
		this.id = id;
		this.origin = origin;
		this.destination = destination;
		this.content = content;
	}

	public SynTtDisplayId getId() {
		return this.id;
	}

	public void setId(SynTtDisplayId id) {
		this.id = id;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	private static final long serialVersionUID = 1L;

}
