package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * SynWeatherStation generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class SynWeatherStation extends LightEntity implements java.io.Serializable {

	private SynWeatherStationId id;
	private String station;

	public SynWeatherStation() {
	}

	public SynWeatherStation(SynWeatherStationId id, String station) {
		this.id = id;
		this.station = station;
	}

	public SynWeatherStationId getId() {
		return this.id;
	}

	public void setId(SynWeatherStationId id) {
		this.id = id;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	private static final long serialVersionUID = 1L;

}
