package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * SynWeatherDisplay generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class SynWeatherDisplay extends LightEntity implements java.io.Serializable {

	private SynWeatherDisplayId id;
	private String station;
	private String content;

	public SynWeatherDisplay() {
	}

	public SynWeatherDisplay(SynWeatherDisplayId id, String station, String content) {
		this.id = id;
		this.station = station;
		this.content = content;
	}

	public SynWeatherDisplayId getId() {
		return this.id;
	}

	public void setId(SynWeatherDisplayId id) {
		this.id = id;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	private static final long serialVersionUID = 1L;

}
