package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * SysEnv generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class SysEnv extends LightEntity implements java.io.Serializable {

	private String var;
	private String content;

	public SysEnv() {
	}

	public SysEnv(String var) {
		this.var = var;
	}

	public SysEnv(String var, String content) {
		this.var = var;
		this.content = content;
	}

	public String getVar() {
		return this.var;
	}

	public void setVar(String var) {
		this.var = var;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	private static final long serialVersionUID = 1L;

}
