package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtBtItt generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtBtItt extends LightEntity implements java.io.Serializable {

	private TtBtIttId id;
	private String origin;
	private String destination;
	private String class_;
	private boolean attValid;

	public TtBtItt() {
	}

	public TtBtItt(TtBtIttId id, String origin, String destination, boolean attValid) {
		this.id = id;
		this.origin = origin;
		this.destination = destination;
		this.attValid = attValid;
	}

	public TtBtItt(TtBtIttId id, String origin, String destination, String class_, boolean attValid) {
		this.id = id;
		this.origin = origin;
		this.destination = destination;
		this.class_ = class_;
		this.attValid = attValid;
	}

	public TtBtIttId getId() {
		return this.id;
	}

	public void setId(TtBtIttId id) {
		this.id = id;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public boolean isAttValid() {
		return this.attValid;
	}

	public void setAttValid(boolean attValid) {
		this.attValid = attValid;
	}

	private static final long serialVersionUID = 1L;

}
