package karrus.shared.hibernate;

import java.util.Date;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtBtIttId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtBtIttId extends LightEntity implements java.io.Serializable {

	private String macSecret;
	private Date timestamp;
	private int travelTime;

	public TtBtIttId() {
	}

	public TtBtIttId(String macSecret, Date timestamp, int travelTime) {
		this.macSecret = macSecret;
		this.timestamp = timestamp;
		this.travelTime = travelTime;
	}

	public String getMacSecret() {
		return this.macSecret;
	}

	public void setMacSecret(String macSecret) {
		this.macSecret = macSecret;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getTravelTime() {
		return this.travelTime;
	}

	public void setTravelTime(int travelTime) {
		this.travelTime = travelTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtBtIttId))
			return false;
		TtBtIttId castOther = (TtBtIttId) other;

		return ((this.getMacSecret() == castOther.getMacSecret()) || (this.getMacSecret() != null
				&& castOther.getMacSecret() != null && this.getMacSecret().equals(castOther.getMacSecret())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
						&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())))
				&& (this.getTravelTime() == castOther.getTravelTime());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMacSecret() == null ? 0 : this.getMacSecret().hashCode());
		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result + this.getTravelTime();
		return result;
	}

	private static final long serialVersionUID = 1L;

}
