package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtBtBoxId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtBtBoxId extends LightEntity implements java.io.Serializable {

	private String site;
	private String serial;

	public TtBtBoxId() {
	}

	public TtBtBoxId(String site, String serial) {
		this.site = site;
		this.serial = serial;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtBtBoxId))
			return false;
		TtBtBoxId castOther = (TtBtBoxId) other;

		return ((this.getSite() == castOther.getSite()) || (this.getSite() != null && castOther.getSite() != null
				&& this.getSite().equals(castOther.getSite())))
				&& ((this.getSerial() == castOther.getSerial()) || (this.getSerial() != null
						&& castOther.getSerial() != null && this.getSerial().equals(castOther.getSerial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSite() == null ? 0 : this.getSite().hashCode());
		result = 37 * result + (getSerial() == null ? 0 : this.getSerial().hashCode());
		return result;
	}

	private static final long serialVersionUID = 1L;

}
