package karrus.shared.hibernate;

import java.util.Date;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtBtMacArchiveId generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtBtMacArchiveId extends LightEntity implements java.io.Serializable {

	private String macSecret;
	private Date timestamp;
	private int rssi;

	public TtBtMacArchiveId() {
	}

	public TtBtMacArchiveId(String macSecret, Date timestamp, int rssi) {
		this.macSecret = macSecret;
		this.timestamp = timestamp;
		this.rssi = rssi;
	}

	public String getMacSecret() {
		return this.macSecret;
	}

	public void setMacSecret(String macSecret) {
		this.macSecret = macSecret;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getRssi() {
		return this.rssi;
	}

	public void setRssi(int rssi) {
		this.rssi = rssi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtBtMacArchiveId))
			return false;
		TtBtMacArchiveId castOther = (TtBtMacArchiveId) other;

		return ((this.getMacSecret() == castOther.getMacSecret()) || (this.getMacSecret() != null
				&& castOther.getMacSecret() != null && this.getMacSecret().equals(castOther.getMacSecret())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
						&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())))
				&& (this.getRssi() == castOther.getRssi());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMacSecret() == null ? 0 : this.getMacSecret().hashCode());
		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result + this.getRssi();
		return result;
	}

	private static final long serialVersionUID = 1L;

}
