package karrus.shared.hibernate;

import java.util.Date;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtBtBox generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtBtBox extends LightEntity implements java.io.Serializable {

	private TtBtBoxId id;
	private Date installationDate;
	private Boolean enabled;
	private String ip;
	private String ipVpn;
	private Date ipLastSeen;
	private Date ipVpnLastSeen;
	private String comment;

	public TtBtBox() {
	}

	public TtBtBox(TtBtBoxId id) {
		this.id = id;
	}

	public TtBtBox(TtBtBoxId id, Date installationDate, Boolean enabled, String ip, String ipVpn, Date ipLastSeen,
			Date ipVpnLastSeen, String comment) {
		this.id = id;
		this.installationDate = installationDate;
		this.enabled = enabled;
		this.ip = ip;
		this.ipVpn = ipVpn;
		this.ipLastSeen = ipLastSeen;
		this.ipVpnLastSeen = ipVpnLastSeen;
		this.comment = comment;
	}

	public TtBtBoxId getId() {
		return this.id;
	}

	public void setId(TtBtBoxId id) {
		this.id = id;
	}

	public Date getInstallationDate() {
		return this.installationDate;
	}

	public void setInstallationDate(Date installationDate) {
		this.installationDate = installationDate;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getIpVpn() {
		return this.ipVpn;
	}

	public void setIpVpn(String ipVpn) {
		this.ipVpn = ipVpn;
	}

	public Date getIpLastSeen() {
		return this.ipLastSeen;
	}

	public void setIpLastSeen(Date ipLastSeen) {
		this.ipLastSeen = ipLastSeen;
	}

	public Date getIpVpnLastSeen() {
		return this.ipVpnLastSeen;
	}

	public void setIpVpnLastSeen(Date ipVpnLastSeen) {
		this.ipVpnLastSeen = ipVpnLastSeen;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	private static final long serialVersionUID = 1L;

}
