package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * TtItinerary generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class TtItinerary extends LightEntity implements java.io.Serializable {

	private TtItineraryId id;
	private String name;
	private Integer nominalTravelTime;
	private Integer maxTravelTime;
	private Integer levelOfServiceThreshold1;
	private Integer levelOfServiceThreshold2;
	private int scale;

	public TtItinerary() {
	}

	public TtItinerary(TtItineraryId id, int scale) {
		this.id = id;
		this.scale = scale;
	}

	public TtItinerary(TtItineraryId id, String name, Integer nominalTravelTime, Integer maxTravelTime,
			Integer levelOfServiceThreshold1, Integer levelOfServiceThreshold2, int scale) {
		this.id = id;
		this.name = name;
		this.nominalTravelTime = nominalTravelTime;
		this.maxTravelTime = maxTravelTime;
		this.levelOfServiceThreshold1 = levelOfServiceThreshold1;
		this.levelOfServiceThreshold2 = levelOfServiceThreshold2;
		this.scale = scale;
	}

	public TtItineraryId getId() {
		return this.id;
	}

	public void setId(TtItineraryId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNominalTravelTime() {
		return this.nominalTravelTime;
	}

	public void setNominalTravelTime(Integer nominalTravelTime) {
		this.nominalTravelTime = nominalTravelTime;
	}

	public Integer getMaxTravelTime() {
		return this.maxTravelTime;
	}

	public void setMaxTravelTime(Integer maxTravelTime) {
		this.maxTravelTime = maxTravelTime;
	}

	public Integer getLevelOfServiceThreshold1() {
		return this.levelOfServiceThreshold1;
	}

	public void setLevelOfServiceThreshold1(Integer levelOfServiceThreshold1) {
		this.levelOfServiceThreshold1 = levelOfServiceThreshold1;
	}

	public Integer getLevelOfServiceThreshold2() {
		return this.levelOfServiceThreshold2;
	}

	public void setLevelOfServiceThreshold2(Integer levelOfServiceThreshold2) {
		this.levelOfServiceThreshold2 = levelOfServiceThreshold2;
	}

	public int getScale() {
		return this.scale;
	}

	public void setScale(int scale) {
		this.scale = scale;
	}

	private static final long serialVersionUID = 1L;

}
