package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * UsrUser generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class UsrUser extends LightEntity implements java.io.Serializable {

	private String login;
	private String password;
	private String email;
	private String credential;

	public UsrUser() {
	}

	public UsrUser(String login, String credential) {
		this.login = login;
		this.credential = credential;
	}

	public UsrUser(String login, String password, String email, String credential) {
		this.login = login;
		this.password = password;
		this.email = email;
		this.credential = credential;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCredential() {
		return this.credential;
	}

	public void setCredential(String credential) {
		this.credential = credential;
	}

	private static final long serialVersionUID = 1L;

}
