package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * WthMorsDiag generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class WthMorsDiag extends LightEntity implements java.io.Serializable {

	private WthMorsDiagId id;
	private Double voltage;

	public WthMorsDiag() {
	}

	public WthMorsDiag(WthMorsDiagId id) {
		this.id = id;
	}

	public WthMorsDiag(WthMorsDiagId id, Double voltage) {
		this.id = id;
		this.voltage = voltage;
	}

	public WthMorsDiagId getId() {
		return this.id;
	}

	public void setId(WthMorsDiagId id) {
		this.id = id;
	}

	public Double getVoltage() {
		return this.voltage;
	}

	public void setVoltage(Double voltage) {
		this.voltage = voltage;
	}

	private static final long serialVersionUID = 1L;

}
