package karrus.shared.hibernate;

import net.sf.gilead.pojo.gwt.LightEntity;

/**
 * WthMeteoData generated by hbm2java.
 *
 * Custom pojo generation. Generated: 28 janv. 2020 16:50:06.
 *
 * @author Denis Jacquet (denis.jacquet@karrus-its.com)
 *
 */
public class WthMeteoData extends LightEntity implements java.io.Serializable {

	private WthMeteoDataId id;
	private Double temperatureAir;
	private Double temperatureDew;
	private Double humidity;
	private Double temperatureRoad;
	private Double temperatureBelowSurf;
	private Integer surfaceState;
	private Double salinity;
	private Double temperatureFreezing;
	private Integer precipitationType;
	private Integer precipitationIntensity;
	private Integer freezingRisk;
	private Integer latency;

	public WthMeteoData() {
	}

	public WthMeteoData(WthMeteoDataId id) {
		this.id = id;
	}

	public WthMeteoData(WthMeteoDataId id, Double temperatureAir, Double temperatureDew, Double humidity,
			Double temperatureRoad, Double temperatureBelowSurf, Integer surfaceState, Double salinity,
			Double temperatureFreezing, Integer precipitationType, Integer precipitationIntensity, Integer freezingRisk,
			Integer latency) {
		this.id = id;
		this.temperatureAir = temperatureAir;
		this.temperatureDew = temperatureDew;
		this.humidity = humidity;
		this.temperatureRoad = temperatureRoad;
		this.temperatureBelowSurf = temperatureBelowSurf;
		this.surfaceState = surfaceState;
		this.salinity = salinity;
		this.temperatureFreezing = temperatureFreezing;
		this.precipitationType = precipitationType;
		this.precipitationIntensity = precipitationIntensity;
		this.freezingRisk = freezingRisk;
		this.latency = latency;
	}

	public WthMeteoDataId getId() {
		return this.id;
	}

	public void setId(WthMeteoDataId id) {
		this.id = id;
	}

	public Double getTemperatureAir() {
		return this.temperatureAir;
	}

	public void setTemperatureAir(Double temperatureAir) {
		this.temperatureAir = temperatureAir;
	}

	public Double getTemperatureDew() {
		return this.temperatureDew;
	}

	public void setTemperatureDew(Double temperatureDew) {
		this.temperatureDew = temperatureDew;
	}

	public Double getHumidity() {
		return this.humidity;
	}

	public void setHumidity(Double humidity) {
		this.humidity = humidity;
	}

	public Double getTemperatureRoad() {
		return this.temperatureRoad;
	}

	public void setTemperatureRoad(Double temperatureRoad) {
		this.temperatureRoad = temperatureRoad;
	}

	public Double getTemperatureBelowSurf() {
		return this.temperatureBelowSurf;
	}

	public void setTemperatureBelowSurf(Double temperatureBelowSurf) {
		this.temperatureBelowSurf = temperatureBelowSurf;
	}

	public Integer getSurfaceState() {
		return this.surfaceState;
	}

	public void setSurfaceState(Integer surfaceState) {
		this.surfaceState = surfaceState;
	}

	public Double getSalinity() {
		return this.salinity;
	}

	public void setSalinity(Double salinity) {
		this.salinity = salinity;
	}

	public Double getTemperatureFreezing() {
		return this.temperatureFreezing;
	}

	public void setTemperatureFreezing(Double temperatureFreezing) {
		this.temperatureFreezing = temperatureFreezing;
	}

	public Integer getPrecipitationType() {
		return this.precipitationType;
	}

	public void setPrecipitationType(Integer precipitationType) {
		this.precipitationType = precipitationType;
	}

	public Integer getPrecipitationIntensity() {
		return this.precipitationIntensity;
	}

	public void setPrecipitationIntensity(Integer precipitationIntensity) {
		this.precipitationIntensity = precipitationIntensity;
	}

	public Integer getFreezingRisk() {
		return this.freezingRisk;
	}

	public void setFreezingRisk(Integer freezingRisk) {
		this.freezingRisk = freezingRisk;
	}

	public Integer getLatency() {
		return this.latency;
	}

	public void setLatency(Integer latency) {
		this.latency = latency;
	}

	private static final long serialVersionUID = 1L;

}
